### PR TITLE
Upgraded protractor to version 4

### PR DESCRIPTION
**Pull request by JesseChezenko-AI**
I ran `grunt default` locally and all the tests passed.

### CODE REVIEW

**Comment by BogdanLivadariu** [comment]
@andreasonny83 any updates on this one ?

**Comment by andreasonny83** [comment]
@BogdanLivadariu no idea why you are tagging me in here as I'm not in the Protractor team.
Anyway, I can see the latest Protractor version is 3.2.0, not sure why you are referring to a version 4. Also, I really don't get the reason of this pull request as the only change is the protractor version inside the `package.json`. Are you sure you know what you're doing here?

**Comment by BogdanLivadariu** [comment]
@andreasonny83 the latest protractor version is `4.0.2`and we would like for `grunt-protractor-runner` to make use of that.

As it stands, we will need to remove the grunt-protractor-runner/node_modules/protractor dir in order to make use of what version of protractor you'll want to use

I've just seen that I've mentioned you by mistake(sorry for any inconvenience), I should have mention @teerapap :) as he is one of the ppl that has write access to this repo :)

**Comment by teerapap** [comment]
grunt-protractor-runner v4.0.0 is released with protractor v4 support. Sorry for late response.

**Pull request closed without merging**
