### PR TITLE
Update to protractor 3.1

### PR DESCRIPTION
**Pull request by bastienmoulia**
Fix issue #144

### CODE REVIEW

**Comment by didlich** [comment]
+1

**Comment by americoneto1** [comment]
+1

**Comment by didlich** [comment]
@bastienmoulia I think the pull request is not up to date, because the latest protractor version is 3.1.1

**Comment by bastienmoulia** [comment]
@didlich Normally it's compatible with all 3.1.X protractor versions.

**Comment by didlich** [comment]
current protractor version is 3.3.0, does it make sense to update?

**Comment by teerapap** [comment]
With '`^3.0.0`', it already matches 3.x.x

> The caret, on the other hand, is more relaxed. It will update you to the most recent major version (the first number). ^1.2.3 will match any 1.x.x release including 1.3.0, but will hold off on 2.0.0.

**Pull request closed without merging**
